### ISSUE TITLE
Bugs after recent update? 

### ISSUE THREAD

**Issue by wenlibin02** [scopus-api/scopus#29]
I installed this package on April 6, it worked fine although there were some minor bugs. Today (April 16) I updated the version and found some problems. 
I typed the following code in ipython (python 2.7) on Mac OS X: 

    from scopus.scopus_api import ScopusAbstract
    ab = ScopusAbstract("2-s2.0-84930616647", view='META', refresh=True) 
    /usr/local/lib/python2.7/site-packages/scopus/scopus_api.pyc in __init__(self, EID, view, refresh)
    239         # Parse authors
    240         authors = xml.find('dtd:authors', ns)
    --> 241         self._authors = [_ScopusAuthor(author) for author in authors]
        242         self._affiliations = [_ScopusAffiliation(aff) for aff
        243                               in xml.findall('dtd:affiliation', ns)]
    TypeError: 'NoneType' object is not iterable

then I tried view='FULL', 

    from scopus.scopus_api import ScopusAbstract
    ab = ScopusAbstract("2-s2.0-84930616647", view='FULL', refresh=True) #it is OK
    print ab.refcount 
    /usr/local/lib/python2.7/site-packages/scopus/scopus_api.pyc in refcount(self)
        146             return self._references.attrib['refcount']
        147         else:
    --> 148             raise TypeError("Could not load article references. "
        149                             "Did you load with view=FULL?")
        150
    
    TypeError: Could not load article references. Did you load with view=FULL?

Other information: 
I installed the package using: ``pip install git+git://github.com/jkitchin/scopus``
updated the package using: ``pip install --upgrade git+git://github.com/jkitchin/scopus``

**Comment by Michael-E-Rose** [comment]
Hi there and sorry for the late consideration of your bug report.  I were just looking into this but the Scopus database seems to be down (I keep getting 500 Server Error).  Hence I can't replicate the bug right now.  Is the error still prevailing with the repo's current version?

**Comment by Michael-E-Rose** [comment]
Now I replicate the error.  It occours both on 3.x and 2.7.

There are two issues.  The first is that you cannot load the object at all view `view='META'`.  The second is that you do not get any references when you load the object with `view='FULL'`.

The second issue first.  This bug was fixed in 030e7918ea6bb939e318632d884d105ce12e9c6e and is live in the development version.  The next update on PyPI is a question of days.

The first issue: When you load with "META" only, the abstract view does not include authors, see http://api.elsevier.com/documentation/retrieval/AbstractRetrievalViews.htm.  But the object should still load properly.  I will fix this in a minute.
