### ISSUE TITLE
Cache for ScopusAbstract does not take view into account

### ISSUE THREAD

**Issue by stijnh** [scopus-api/scopus#66]
ScopusAbstract does not take view parameter into account when fetching items from the cache. This is problematic when requesting the same abstract multiple times, but for different views. For example (for empty cache):

```
a = ScopusAbstract('2-s2.0-84937398919', view='META') # Correct: Fetches META from API.
b = ScopusAbstract('2-s2.0-84937398919', view='FULL') # Error: Fetches META from cache again.
```

I noticed this when I switched from META to META_ABS in my script, and not getting the abstracts.  Clearing the cache resolved the issue.

**Comment by Michael-E-Rose** [comment]
Hi stijnh!  Yes, this behavior is correct.  scopus does not save the view when caching articles.  I think we should not do this simply because it would create excess files where in fact one would suffice:  The file with the highest view parameter, because it always includes information for lower view parameters.

The simple solution to this is to always load files with the [highest view parameter](https://dev.elsevier.com/guides/AbstractRetrievalViews.htm), in this case `'FULL'`.  The reason `'FULL'` is not the standard value is that it might be restricted so some users.  But I never came across such a case.

We can expand the documentation, stating that the view parameter only takes effect upon refreshing or on first download.  Do you think that's a good solution?

**Comment by stijnh** [comment]
Expanding the documentation is indeed a good solution and would have saved me some time debugging. Ideally, there would be multiple caches for META, META_ABS, and FULL (different directories maybe?) so it always returns the expected abstract. However, this might be more trouble than it's worth and, like you said, would increase the number of cached files.
