### ISSUE TITLE
Redesign API to use Pandas

### ISSUE THREAD

**Issue by antoniocaruso** [scopus-api/scopus#67]
It would be really interesting if some of the API could return pandas Dataframes.

Moreover, I was not able to understand why in some case the hindex showed in the scopus page of an author is greater then the value that I get using the API.
I was not able also to ge the total number of papers. (Do I have to call author_impact_factor(..) ) with
a specific year? It seems it start from 2014.
How do I get the total number of papers of an author?

**Comment by Michael-E-Rose** [comment]
Hi Antonio and thanks for the issue!

There are three things here:

1. We not want to return pandas DataFrames because pandas is not included in the python base package.  Returning a pandas object would require that people install pandas as well.  The current approach is to return python base objects that can easily be converted into pandas DataFrames.  These objects are for example named tuples.

2. If you have an example where hindex on scopus.com and hindex obtained via the scopus package differ I can look into it.  It might be that the definition of what counts as publiction differs.  Should editorials, comments, books, be counted or not?

3. There are several ways, all documented on https://scopus.readthedocs.io/en/latest/reference/scopus.ScopusAuthor.html:  Either you use `.n_journal_articles()` or `.n_yearly_publications()` or `.ndocuments`.
