### ISSUE TITLE
Refactor tests so that some are skipped if the user isn't a subscriber

### ISSUE THREAD

**Issue by crew102** [scopus-api/scopus#91]
Right now it's really difficult for non-subscribers to contribute to the package b/c the testing framework assumes that the user is a subscriber. For example, all of the `AbstractRetrieval` tests assume that the user has access to the "FULL" view of the abstract retrieval API, but they only have access to the "META" view (https://dev.elsevier.com/api_key_settings.html). Cases like this require that the non-subscriber goes through failing tests one by one to determine which ones are failing b/c they don't have access to certain views/APIs and which ones are failing b/c they simply broke something in the code. Obviously it's not ideal to totally ignore the functionality that subscribers have when writing tests (i.e., to only test functionality that both subscribers and non-subscribers have), but I'm wondering if there's a solution/refactoring of the tests that will not place such a heavy emphasis on the subscriber use case.

**Comment by Michael-E-Rose** [comment]
At first this sounds a bit difficult and counter-intuitive:  Tests should be all-inclusive.  If we allow partial tests, how can we be sure that a feature didn't break something somewhere else?

However, even right now our testing environment is quite difficult, as there is no CI - everything needs to run on the local machine beforehand, and there are some tests that many people can't perform because their key likely doesn't cover that API (CitationOverview is one such candidate).  In practice, I am testing new features on my two machines manually anyways.

Which APIs would be affected?  Do all of them offer information to non-subscribers?

**Comment by crew102** [comment]
Not all of them offer info for subscribers. I was imagining a solution where a user's subscription status would be checked by trying to hit one of the subscriber-only APIs, and if the user is determined to be a non-subscriber based on that, certain tests would be skipped. Thoughts?

**Comment by Michael-E-Rose** [comment]
I think this solution is impractical.  Basically, there's always a test query which affects download time negatively and also puts unnecessary stress on the API key.
